# Boolean toggle whether you want to receive new updates everytime your server restart if a new update is released.
# If set to "false" you will not receive new updates and need to manually update it yourself.
auto-update: true

# LiteXpansion items (iridium) will be used as recipes for FN PowerXpansion
# This will only work if LiteXpansion is installed and value is set to true
LiteX-Recipe-Integration: true

# SimpleMaterialGenerators items as some recipes for FN Material Generators
# Same as above, will only work if SMG is installed and value is set to true
SMG-Recipe-Integration: true

# Use 1.17 items (such as amethyst, copper, calcite, etc) as some recipes for FN Machinery Items
# This will only work if server is running 1.17 and value is set to true
New-Recipe-Integration: true

# Armor Effects Update, the time to update the armor effects in seconds (i.e FN Gears of Friction permanent effects)
# For now the chestplate only has a permanent effect at level 30
armor-update-period: 10

# Enable or disable chat changelogs, this changelog get sent only when players join the server for the first time after server restart
# If disabled no more changelogs will be sent, requires server restart
Enable-One-Time-Chat-Changelog: true