# Boolean toggle whether you want to receive new updates everytime your server restart if a new update is released.
# If set to "false" you will not receive new updates and need to manually update it yourself.
auto-update: true

# LiteXpansion items (iridium) will be used as recipes for FN PowerXpansion
# This will only work if LiteXpansion is installed and value is set to true
LiteX-Recipe-Integration: true

# SimpleMaterialGenerators items as some recipes for FN Material Generators
# Same as above, will only work if SMG is installed and value is set to true
SMG-Recipe-Integration: true

# Use 1.17 items (such as amethyst, copper, calcite, etc) as some recipes for FN Machinery Items
# This will only work if server is running 1.17 and value is set to true
New-Recipe-Integration: true

# Slimefun Custom addon by FN_FAL113, huge thanks to Walshy and Jeff (LiteXpansion) for letting me use their utils
# You can change the values here, it requires server restart to take effect.

# FN Power Xpansion Rank 1
FN-Xpansion-Rank1-Dayrate: 236
FN-Xpansion-Rank1-Nightrate: 138
FN-Xpansion-Rank1-Output: 20
FN-Xpansion-Rank1-Capacity: 600000

# FN Power Xpansion Rank 2
FN-Xpansion-Rank2-Dayrate: 472
FN-Xpansion-Rank2-Nightrate: 276
FN-Xpansion-Rank2-Output: 40
FN-Xpansion-Rank2-Capacity: 700000

# FN Power Xpansion Rank 3
FN-Xpansion-Rank3-Dayrate: 944
FN-Xpansion-Rank3-Nightrate: 552
FN-Xpansion-Rank3-Output: 60
FN-Xpansion-Rank3-Capacity: 800000

# FN Power Xpansion Rank 4
FN-Xpansion-Rank4-Dayrate: 1888
FN-Xpansion-Rank4-Nightrate: 1104
FN-Xpansion-Rank4-Output: 120
FN-Xpansion-Rank4-Capacity: 900000

# FN Power Xpansion Rank 5
FN-Xpansion-Rank5-Dayrate: 3776
FN-Xpansion-Rank5-Nightrate: 2208
FN-Xpansion-Rank5-Output: 240
FN-Xpansion-Rank5-Capacity: 1000000

# FN Power Xpansion Rank 6
FN-Xpansion-Rank6-Dayrate: 7552
FN-Xpansion-Rank6-Nightrate: 4416
FN-Xpansion-Rank6-Output: 480
FN-Xpansion-Rank6-Capacity: 1500000

# FN Power Xpansion Rank 7
FN-Xpansion-Rank7-Dayrate: 15104
FN-Xpansion-Rank7-Nightrate: 8832
FN-Xpansion-Rank7-Output: 960
FN-Xpansion-Rank7-Capacity: 2000000

# FN Power Xpansion Rank 8
FN-Xpansion-Rank8-Dayrate: 18880
FN-Xpansion-Rank8-Nightrate: 11040
FN-Xpansion-Rank8-Output: 1200
FN-Xpansion-Rank8-Capacity: 3000000

# FN Power Xpansion Rank 9
FN-Xpansion-Rank9-Dayrate: 22656
FN-Xpansion-Rank9-Nightrate: 13248
FN-Xpansion-Rank9-Output: 1440
FN-Xpansion-Rank9-Capacity: 4500000

# FN Power Xpansion Rank 10
FN-Xpansion-Rank10-Dayrate: 26432
FN-Xpansion-Rank10-Nightrate: 15456
FN-Xpansion-Rank10-Output: 1680
FN-Xpansion-Rank10-Capacity: 6750000

# FN Power Xpansion Rank 11
FN-Xpansion-Rank11-Dayrate: 30208
FN-Xpansion-Rank11-Nightrate: 17664
FN-Xpansion-Rank11-Output: 1920
FN-Xpansion-Rank11-Capacity: 9000000

# FN Power Xpansion Rank 12
FN-Xpansion-Rank12-Dayrate: 45312
FN-Xpansion-Rank12-Nightrate: 26496
FN-Xpansion-Rank12-Output: 2880
FN-Xpansion-Rank12-Capacity: 12000000


# This is where you can configure tick rates for each Material Generator
# This is a custom addon for slimefun by FN_FAL113 based on SMG addon by waleks (addon dev)

# Rate for Clay Generator
FN_CLAY-TickRate: 32

# Rate for Warp Nylium Generator
FN_WARPED_NYLIUM-TickRate: 48

# Rate for Terracotta Generator
FN_TERRACOTTA-TickRate: 84

# Rate for Bone Generator
FN_BONE-TickRate: 256

# Rate for Diamond Generator
FN_DIAMOND-TickRate: 192

# Rate for Emerald Generator
FN_EMERALD-TickRate: 218

# Rate for Dirt Generator
FN_Dirt-TickRate: 36

# Rate for Honey Comb Generator
FN_HONEYCOMB-TickRate: 52


# Tick based power is multiplied by 2, The value here is in Seconds and will be converted in ticks in game. Ticks is slower than per seconds
# Buffer is the actual capacity that the solar generator can store
# This is a Custom Slimefun Addon by FN_FAL113
# Change Lore if you intend to make the generator work at Night by changing the values of 'Tier#-power#-night:'

# Power settings for FN Solar Gen Tier I
Tier1-power1: 512
Tier1-power1-night: 0
Buffer1: 2048
Tier1-Lore: "&eGenerator works during Day only"

# Power settings for FN Solar Gen Tier III
Tier2-power2: 1024
Tier2-power2-night: 0
Buffer2: 4096
Tier2-Lore: "&eGenerator works during Day only"

# Power settings for FN Solar Gen Tier III
Tier3-power3: 2048
Tier3-power3-night: 0
Buffer3: 6144
Tier3-Lore: "&eGenerator works during Day only"

# Power settings for FN Solar Gen Tier IV
Tier4-power4: 4096
Tier4-power4-night: 0
Buffer4: 12288
Tier4-Lore: "&eGenerator works during Day only"

# Power settings for FN Solar Gen Tier V
Tier5-power5: 6144
Tier5-power5-night: 0
Buffer5: 24576
Tier5-Lore: "&eGenerator works during Day only"

# Power settings for FN Solar Gen Tier VI
Tier6-power6: 8192
Tier6-power6-night: 0
Buffer6: 49152
Tier6-Lore: "&eGenerator works during Day only"

# Power settings for FN Solar Gen Tier VI
Tier7-power7: 10240
Tier7-power7-night: 0
Buffer7: 98304
Tier7-Lore: "&eGenerator works during Day only"

# Power settings for FN Solar Gen Tier VI
Tier8-power8: 12288
Tier8-power8-night: 0
Buffer8: 196608
Tier8-Lore: "&eGenerator works during Day only"

# Tick rate settings for the Electric Block Breaker
# Lower ticks the faster it breaks a block
E-block-breaker1-tickRate: 12
E-block-breaker2-tickRate: 6
E-block-breaker3-tickRate: 2

# Modify here the Staff max uses value
Staff-of-Locomotion: 10
Staff-of-Invisibility: 10
Staff-of-Teleportation: 10
Staff-of-HellFire: 10
Staff-of-DeepFreeze: 10
Staff-of-Confusion: 10
Staff-of-Gravity: 10

# FN Gears of Friction (Unbreakability)
# Default is set to false (if set to true, will apply only on newly crafted gears)
FN-Helmet-Unbreakable: false
FN-Chestplate-Unbreakable: false
FN-Leggings-Unbreakable: false
FN-boots-Unbreakable: false