name: Build and Deploy to Blob-Builds

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  blob-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Build with Maven
        run: mvn package

      - name: Set Filename Env Variables
        run: |
          echo "PROJECT_NAME=$(mvn help:evaluate -Dexpression=project.name -q -DforceStdout)" >> "$GITHUB_ENV"
          echo "PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_ENV"

      - name: Upload to Blob Builds
        uses: WalshyDev/blob-builds/gh-action@main
        with:
          project: FNAmplifications
          apiToken: ${{ secrets.BLOB_BUILDS_API_TOKEN }}
          file: ./target/${{ env.PROJECT_NAME}} v${{ env.PROJECT_VERSION }}.jar
          releaseNotes: ${{ github.event.head_commit.message }}
